[SERVER]
host = "localhost"
port = 3131

[DATABASE]
dsn = ""

[LOGGING]
# 0 = NOTSET
# 10 = DEBUG
# 20 = INFO (DEFAULT)
# 30 = WARNING
# 40 = ERROR
# 50 = CRITICAL
level = 20

[OPTIONS]
enable_signups = true
max_url_length = 1024
min_url_length = 25
github_url = ""
discord_url = ""

[LIMITS]
create = {"rate" = 8, "per" = 60}
qr = {"rate" = 12, "per" = 60}
stats = {"rate" = 30, "per" = 60}
redirect = {"rate" = 2000, "per" = 86400}
homepage = {"rate" = 2000, "per" = 86400}

[DOMAIN]
name = "localhost"

[REDIS]
host = "localhost"
port = 6379
db = 0

[SESSIONS]
secret = "" # Large random string; use print(secrets.token_urlsafe(128)) to generate for example
max_age = 604800  # seconds... 604800 = 1 week
