[SERVER]
host = "localhost"
port = 3131

[DATABASE]
dsn = ""

[LOGGING]
# 0 = NOTSET
# 10 = DEBUG
# 20 = INFO (DEFAULT)
# 30 = WARNING
# 40 = ERROR
# 50 = CRITICAL
level = 20

[OPTIONS]
enable_signups = true
max_url_length = 1024
min_url_length = 25