CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10000),
    email TEXT UNIQUE NOT NULL,
    moderator BOOLEAN NOT NULL DEFAULT false,
    donator BOOLEAN NOT NULL DEFAULT false,
    token TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS redirects (
    id TEXT PRIMARY KEY,
    uid BIGINT,
    expiry TIMESTAMPTZ,
    location TEXT NOT NULL,
    FOREIGN KEY(uid) REFERENCES users(id)
);